/** 阶段 4 Agent 分析资源上限（集中定义）。 */
export const AGENT_LIMITS = {
  MAX_CANDIDATES: 200,
  MAX_REQUEST_BYTES: 128 * 1024,
  MAX_EVIDENCE_PER_CANDIDATE: 8,
  MAX_TEXT_FIELD_LENGTH: 256,
  MAX_BASIS_ITEMS: 8,
  MAX_BASIS_ITEM_LENGTH: 256,
  MAX_RECOMMENDATIONS: 200,
  MAX_SUMMARY_HEADLINE_LENGTH: 256,
  MAX_SUMMARY_OVERVIEW_LENGTH: 2048,
  ANALYSIS_TIMEOUT_MS: 60_000,
  ANALYSIS_MAX_TOKENS: 4096,
  /** 多轮编排累计消息体上限（含 system / user / assistant）。 */
  MAX_CONVERSATION_BYTES: 256 * 1024
} as const
