/** Provider 输入长度上限（IPC 与存储层共用）。 */
export const PROVIDER_INPUT_LIMITS = {
  BASE_URL_MAX_LENGTH: 2048,
  MODEL_MAX_LENGTH: 128,
  API_KEY_MAX_LENGTH: 512,
  PROFILE_NAME_MAX_LENGTH: 64,
  PROFILE_ID_MAX_LENGTH: 64,
  MAX_PROFILES: 20
} as const
