export const USER_EXPERIENCE_LIMITS = {
  MAX_ENTRIES: 200,
  MAX_NAME_LENGTH: 80,
  MAX_REASON_LENGTH: 240,
  MAX_RELATIVE_PATH_SUFFIX_LENGTH: 160,
  MAX_SOFTWARE_NAME_LENGTH: 80,
  MAX_JSON_BYTES: 256 * 1024,
  MAX_ID_LENGTH: 80,
  MAX_SESSION_ID_LENGTH: 128,
  MAX_CANDIDATE_ID_LENGTH: 128,
  MAX_ISOLATED_ENTRIES: 100,
  MAX_ISOLATED_JSON_BYTES: 64 * 1024,
  MAX_CORRUPT_BACKUPS: 5
} as const
